name: 'ghactiontest'
description: 'Greet someone, record the time, and run Slither Analysis'
inputs:
  name-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: 'composite'
  steps:
    - name: Run Greet Script
      run: |
        node dist/index.js "${{ inputs.name-to-greet }}"
      shell: bash
    - name: Record Time
      run: echo "Current time is $(date)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Run Slither Analysis
      uses: crytic/slither-action@v0.4.0
      with:
        target: 'contracts/'  # Specify the directory containing your Solidity files
        sarif: results.sarif