name: 'Custom Action with Slither'
description: 'Run custom Node.js code and Slither analysis'
inputs:
  name-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
  slither-target:
    description: 'Target directory or file for Slither analysis'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Run custom Node.js code
      run: node ${{ github.action_path }}/dist/index.js "${{ inputs.name-to-greet }}"
      shell: bash

    - name: Run Slither Analysis
      uses: crytic/slither-action@v0.3.0
      with:
        target: ${{ inputs.slither-target }}
        sarif: results.sarif